<?php
print '
<h1>Welcome to Formula 1</h1>

<figure>
    <img src="Slike/grid.jpg" alt="HTML5" title="HTML5">
    <figcaption>Formula 1 has 10 teams of 2 drivers. The top 20 racers in the world are competing for the grand prize of being the world champion.</figcaption>
</figure>

<p>Formula 1® racing began in 1950 and is the world’s most prestigious motor racing competition, as well as the world’s most popular annual sporting series: The 2019 FIA Formula One World Championship runs from March to December and spans 21 races in 21 countries across four continents. Formula One World Championship Limited is part of Formula 1 and holds the exclusive commercial rights to the FIA Formula One World Championship.</p>

<p>Formula One (more commonly known as Formula 1 or F1) is the highest class of international racing for open-wheel single-seater formula racing cars sanctioned by the Fédération Internationale de l\'Automobile (FIA). The FIA Formula One World Championship has been one of the premier forms of racing around the world since its inaugural season in 1950. The word formula in the name refers to the set of rules to which all participants cars must conform. A Formula One season consists of a series of races, known as Grands Prix. Grands Prix take place in multiple countries and continents around the world on either purpose-built circuits or closed public roads.</p>

<p>A points system is used at Grands Prix to determine two annual World Championships: one for the drivers, and one for the constructors (the teams). Each driver must hold a valid Super Licence, the highest class of racing licence issued by the FIA, and the races must be held on tracks graded "1", the highest grade-rating issued by the FIA for tracks.</p>

<p>Formula One cars are the fastest regulated road-course racing cars in the world, owing to very high cornering speeds achieved through generating large amounts of aerodynamic downforce. Much of this downforce is generated by front and rear wings, which have the side effect of causing severe turbulence behind each car. The turbulence reduces the downforce generated by the cars following directly behind, making it hard to overtake. Major changes made to the cars for the 2022 season have resulted in greater use of ground effect aerodynamics and modified wings to reduce the turbulence behind the cars, with the goal of making overtaking easier. The cars are dependent on electronics, aerodynamics, suspension and tyres. Traction control, launch control, and automatic shifting, plus other electronic driving aids, were first banned in 1994. They were briefly reintroduced in 2001, and have more recently been banned since 2004 and 2008, respectively.</p>

<p>With the average annual cost of running a team – designing, building, and maintaining cars, pay, transport – being approximately £220,000,000 (or $265,000,000), its financial and political battles are widely reported. On 23 January 2017, Liberty Media completed its acquisition of the Formula One Group, from private-equity firm CVC Capital Partners for £6.4bn ($8bn).</p>

<p>Source <a href="https://en.wikipedia.org/wiki/Formula_One"> LoremIpsum</a></p>

<p>Social media <br>

    <a href="https://www.facebook.com/Formula1" target="_blank"> <img src="Slike/facebook.png" alt="facebook" title="facebook" style="width:24px; margin-top:0.4em"></a>
    <a href="https://www.linkedin.com/company/formula-one-management-ltd/?originalSubdomain=uk" target="_blank"> <img src="SLike/linkedin.png" alt="linkedin" title="linkedin" style="width:24px; margin-top:0.4em"> </a>
    <a href="https://twitter.com/F1" target="_blank"><img src="Slike/twitter.png" alt="twitter" title="twitter" style="width:24px; margin-top:0.4em"></a>
    
</p>';
?>
